version: '3.8'

services:
  
  trader.identity-db:
    image: postgres:15.5
    hostname: trader.identity-db
    restart: always
    environment:
      POSTGRES_PASSWORD: RwPap27k5VnZTqVt
    volumes:
      - ./init-queries/init-identity.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8010:5432"