version: '3.8'

services:
  trader.inventory-db:
    image: postgres:15.5
    hostname: trader.inventory-db
    restart: always
    environment:
      POSTGRES_PASSWORD: RwPap27k5VnZTqVt
    volumes:
      - ./init-queries/init-inventory.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8020:5432"