version: '3.8'

services:
  trader.s3:
    image: minio/minio
    hostname: trader.s3
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: LgN0mn77lPdkfOCEaSO9
      MINIO_ACCESS_KEY: 7wNyb4lMFhIJ1bv0c4ws
      MINIO_SECRET_KEY: zVYrAVtFW4Fhu8Kyu6u7Of4xEPc4nUFg8qJ6MpF1
    command: server --console-address ":10000" --address ":10001" /data

volumes:
  minio_storage: { }