apiVersion: v1
kind: Pod
metadata:
  name: identity-db
  labels:
    app: identity-db
spec:
  containers:
    - name: identity-db
      image: opentrader/identity-db:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_PASSWORD
          value: 5Q0SltGdy1mKy2Re
  restartPolicy: Always