apiVersion: v1
kind: Pod
metadata:
  name: mq.rabbit
  labels:
    app: mq.rabbit
spec:
  containers:
    - name: mq.rabbit
      image: opentrader/mq-rabbit:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5672
        - containerPort: 15672
  restartPolicy: Always